version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    rebase-strategy: 'disabled'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
    directory: '/'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'increase'
